# Generated by Django 3.0.5 on 2022-11-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20221107_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldname',
            name='old_eemail',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
