# Generated by Django 3.0.5 on 2022-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('company', models.CharField(max_length=70)),
                ('salary', models.IntegerField()),
                ('bank', models.CharField(max_length=70)),
            ],
        ),
    ]
