# Generated by Django 4.1.2 on 2022-10-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstid', models.IntegerField()),
                ('cstname', models.CharField(max_length=70)),
                ('cstemail', models.EmailField(max_length=70)),
                ('cstpass', models.CharField(max_length=70)),
                ('cstbill', models.IntegerField(max_length=70)),
            ],
        ),
    ]
