# Generated by Django 4.1.2 on 2022-10-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.IntegerField()),
                ('custname', models.CharField(max_length=70)),
                ('custemail', models.EmailField(max_length=70)),
                ('custpass', models.CharField(max_length=70)),
                ('custbill', models.IntegerField(max_length=70)),

            ],
        ),
    ]
